name: Testing Pipeline

on:
  workflow_dispatch:

jobs:
  My_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Getting My Repo
        uses: actions/checkout@v4
      - name: System Info
        run: | 
          pwd
          ls -la
          echo "Hello from GitHub Actions"
      - name: Creating New DIR
        run: mkdir practice
      - name: Getting into new DIR and create file
        working-directory: practice
        run: | 
          pwd
          touch kali.txt && echo "Hi there from Kali.txt" >> kali.txt
          ls -la
      - name: Creating ENV Variable
        env:
          MY_NAME: AHMED
        run: echo "My name is $MY_NAME"
          
     # - name: checking file exists
     #  run: |
     #     echo "Start searching"
     #     my_file=package.json
     #     if [ -f "$my_file" ];then
     #      echo "The $my_file is existing"
     #     else
     #       echo "File doesn't exist"
     #     fi
