name: Testing Pipeline

on:
  schedule:
    - cron: 0 10 7 10 *
  workflow_dispatch:
env:
  IMAGE_NAME: first-test
  IMAGE_TAG: ${{ github.sha }}

jobs:
  My_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Getting My Repo
        uses: actions/checkout@v4
      - name: System Info
        run: | 
          pwd
          ls -la
          echo "Hello from GitHub Actions"
      - name: Creating New DIR
        run: mkdir practice
      - name: Getting into new DIR and create file
        working-directory: practice
        run: | 
          pwd
          touch kali.txt && echo "Hi there from Kali.txt" >> kali.txt
          ls -la
      - name: Creating ENV Variable
        env:
          MY_NAME: AHMED
        run: echo "My name is $MY_NAME"
      - name: SetUp NodeJS
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 22.x
      - name: Check NodeJS Version
        run: |
          node --version
          npm --version
      - name: Install Dependencies
        run: npm install
      - name: Testing Node
        run: |
          echo "Start Testing"
          npm test
          sleep 1
          echo "Test has finished with exit code $?"

  Build_Stage:
    runs-on: ubuntu-latest
    needs: My_setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Logging to DockerHub
        uses: docker/login-action@v4.6.0
        with:
          username: ${{ secrets.DOCK_USERNAME }}
          password: ${{ secrets.DOCK_PASS }}
      - name: Building Image
        run: |
          docker build --tag ${{ secrets.DOCK_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker images
      - name: Pushing Image to DockerHub
        run: docker push ${{ secrets.DOCK_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
  Deploy:
    runs-on: ubuntu-latest
    needs: Build_Stage
    steps:
      - name: Connecting to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCK_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker stop My-first-container || true
            docker rm My-first-container || true
            docker run -d \
              --name My-first-container \
              -p 3000:3000 \
              ${{ secrets.DOCK_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Checking connection       
        run: |
           sleep 3
           curl -sL http://${{ secrets.SERVER_IP }}:3000
     # - name: checking file exists
     #  run: |
     #     echo "Start searching"
     #     my_file=package.json
     #     if [ -f "$my_file" ];then
     #      echo "The $my_file is existing"
     #     else
     #       echo "File doesn't exist"
     #     fi
