name: Testing Pipeline

on:
  workflow_dispatch:

jobs:
  My_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Getting My Repo
        uses: actions/checkout@v4
      - name: Check my local Repo content
        run: ls -la
      - name: checking file exists
        run: |
          echo "Start searching"
          my_file=package.json
          if [ -f $my_file ];then
            echo "The $my_file is existing"
          else
            echo "File doesn't exist"
          fi
