name: Medo_is_testing

on:
  workflow_dispatch:

jobs:
  run_node:
    strategy:
      fail-fast: false
      matrix:
        oss: [ubuntu-latest,windows-latest]
        node-version: [24.x,22.x]
    runs-on: ${{ matrix.oss }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6.5.0
      with:
        node-version: ${{matrix.node-version}}
    - name: Testing shell
      run: echo "Meow is the best"
    #- name: Checking npm
    #  run: |
    #    echo "Meow is here"
    #    ls -la .
    - name: Testing NPM
      run: npm test
            
  
  
